# Generated by Django 2.2.6 on 2019-11-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communities_communitycreator'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='communityCreationDate',
            field=models.DateField(null=True),
        ),
    ]
