# Generated by Django 2.2.6 on 2019-11-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20191107_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatypes',
            name='relatedCommunity',
            field=models.ForeignKey(help_text='Select related community', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relcommunity', to='community.Communities'),
        ),
    ]
