# Generated by Django 2.2.6 on 2019-11-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20191107_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='communityPrv',
            field=models.BooleanField(default=False),
        ),
    ]
