# Generated by Django 2.2.6 on 2019-11-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20191112_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='communityPopularity',
            field=models.IntegerField(null=True),
        ),
    ]
