# Generated by Django 2.2.6 on 2019-11-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_auto_20191125_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='communityTags',
            field=models.CharField(help_text='Enter community hash', max_length=2000, null=True),
        ),
    ]
