# Generated by Django 2.2.6 on 2019-11-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_communities_communitytags'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='datatypeTags',
            field=models.CharField(help_text='Enter datatype Tags', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='communities',
            name='communityTags',
            field=models.CharField(help_text='Enter community Tags', max_length=2000, null=True),
        ),
    ]
