# Generated by Django 2.2.6 on 2019-11-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_auto_20191125_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='datatypeHash',
            field=models.CharField(help_text='Enter datatype hash', max_length=200, null=True),
        ),
    ]
