# Generated by Django 2.2.6 on 2019-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter community name', max_length=200, null=True)),
                ('description', models.CharField(help_text='Enter community description', max_length=200, null=True)),
                ('communityHash', models.CharField(help_text='Enter community hash', max_length=200, null=True)),
                ('communityPrv', models.CharField(help_text='community private or not', max_length=200, null=True)),
                ('communityPhoto', models.CharField(help_text='community photo', max_length=200, null=True)),
                ('communityPopularity', models.CharField(help_text='community private or not', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='communityUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(help_text='Enter your nickname', max_length=200, null=True)),
                ('userName', models.CharField(help_text='Enter your username', max_length=200, null=True)),
                ('userSurname', models.CharField(help_text='Enter your surname', max_length=200, null=True)),
                ('userMail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(help_text='Enter your password', max_length=200, null=True)),
                ('creationDate', models.DateField(null=True)),
                ('communityPoint', models.CharField(help_text='Community Point', max_length=200, null=True)),
                ('userPhoto', models.CharField(help_text='Community Point', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datatypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter ypur datatype', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryHash', models.CharField(help_text='Enter name of type', max_length=200, null=True)),
                ('propertyName', models.CharField(help_text='Enter name of type', max_length=200, null=True)),
                ('propertyValue', models.CharField(help_text='Enter name of type', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Primitives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your primitive data types', max_length=200, null=True)),
            ],
        ),
    ]
