# Generated by Django 2.2.6 on 2019-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communities_communitycreationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatatypeFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter ypur datatype', max_length=200, null=True)),
            ],
        ),
    ]
