# Generated by Django 2.2.6 on 2019-11-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_datatypefields'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='communityMembers',
            field=models.ManyToManyField(help_text='Select members', related_name='members', to='community.communityUsers'),
        ),
        migrations.AlterField(
            model_name='communities',
            name='communityCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='community.communityUsers'),
        ),
    ]
