# Generated by Django 2.2.6 on 2019-11-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20191107_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='relatedCommunity',
            field=models.ForeignKey(help_text='Select related community', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Communities'),
        ),
    ]
