# Generated by Django 2.2.6 on 2019-11-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='communityCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communityUsers'),
        ),
    ]
