# Generated by Django 2.2.6 on 2019-11-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20191107_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypefields',
            name='fieldCreationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datatypefields',
            name='fieldsCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fieldsecreator', to='community.communityUsers'),
        ),
        migrations.AddField(
            model_name='datatypefields',
            name='fieldsRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datatypefields',
            name='fronttableShow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datatypefields',
            name='relatedComm',
            field=models.ForeignKey(help_text='Select related datatype', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Communities'),
        ),
        migrations.AddField(
            model_name='datatypefields',
            name='relatedDatatype',
            field=models.ForeignKey(help_text='Select related datatype', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Datatypes'),
        ),
        migrations.AddField(
            model_name='datatypefields',
            name='relatedPrimitives',
            field=models.ForeignKey(help_text='Select related primitive', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Primitives'),
        ),
        migrations.AlterField(
            model_name='communities',
            name='communityCreationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='communityusers',
            name='creationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
