# Generated by Django 2.2.6 on 2019-11-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20191107_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatypefields',
            old_name='fieldsCreator',
            new_name='fieldCreator',
        ),
        migrations.RenameField(
            model_name='datatypefields',
            old_name='fieldsRequired',
            new_name='fieldRequired',
        ),
    ]
