# Generated by Django 2.2.6 on 2019-11-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_auto_20191110_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communityUsers'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='relatedCommunityforPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Communities'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='relatedDatatypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Datatypes'),
        ),
    ]
