# Generated by Django 2.2.6 on 2019-11-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_auto_20191111_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatypefields',
            name='fieldCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communityUsers'),
        ),
    ]
