# Generated by Django 2.2.6 on 2019-12-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_datatypes_datatypehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypefields',
            name='enumerations',
            field=models.CharField(help_text='Enter the Enumerations', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datatypefields',
            name='name',
            field=models.CharField(help_text='Enter your datatype', max_length=200, null=True),
        ),
    ]
