# Generated by Django 2.2.6 on 2019-12-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_posts_posttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcreator', to='community.communityUsers'),
        ),
    ]
