# Generated by Django 2.2.6 on 2019-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_auto_20191209_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communities',
            name='communityPopularity',
        ),
        migrations.AddField(
            model_name='communities',
            name='communityPopularity',
            field=models.ManyToManyField(help_text='Vote', related_name='votes', to='community.communityUsers'),
        ),
    ]
