# Generated by Django 2.2.6 on 2019-12-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_auto_20191212_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttags',
            name='postTag',
        ),
        migrations.AddField(
            model_name='posttags',
            name='realtedPostTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postsTag', to='community.Posts'),
        ),
    ]
