# Generated by Django 2.2.6 on 2019-12-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_auto_20191212_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttags',
            old_name='realtedPostTag',
            new_name='relatedPostTag',
        ),
    ]
