# Generated by Django 2.2.6 on 2019-12-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_auto_20191213_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttags',
            name='tagItem',
            field=models.CharField(help_text='Enter Community Tag Item', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='posttags',
            name='tagName',
            field=models.CharField(help_text='Enter Post Tag', max_length=2000, null=True),
        ),
    ]
