# Generated by Django 2.2.6 on 2019-10-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200, null=True)),
                ('nickname', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200, null=True)),
            ],
        ),
    ]
